# Site settings
author: Manuel Baez Diz
title: Why I decided to study Software Engeneering at Flatiron
header-img: img/home-bg.png
email: baezdiazm@yahoo.com
copyright_name: Manuel Baez Diz
description: > # this means to ignore newlines until "baseurl:"
  Story time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  baezdiazm

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
